language: ruby
sudo: false
script: bundle exec rspec
before_script:
  - git config --global user.email "nobody@example.com"
  - git config --global user.name "Nobody Doe"
cache:
  - bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
matrix:
  fast_finish: true
